project:
  type: website
  output-dir: docs

website:
  title: "Luíza Helena Pereira Lúcio"
  description: "Estatística | Análise de Dados | R & Python"
  
  navbar:
    left:
      - href: index.qmd
        text: Início / Home
      - href: sobre.qmd
        text: Sobre / About
      - href: projetos.qmd
        text: Projetos / Projects
      - href: curriculo.qmd
        text: Curriculos / CV
      - href: contato.qmd
        text: Contato / Contact
    right:
      - icon: github
        href: https://github.com/luizalucio
        aria-label: GitHub
      - icon: linkedin
        href: https://linkedin.com/in/luizahplucio
        aria-label: LinkedIn

  page-footer:
    center: |
      Feito com ❤️ usando [Quarto](https://quarto.org) · Made with ❤️ using [Quarto](https://quarto.org)

  open-graph: true
  twitter-card: true

format:
  html:
    theme:
      - flatly
      - styles.scss
    toc: false
    smooth-scroll: true
    code-fold: true
    lang: pt-BR
